### ISSUE TITLE
Importer is stuck when the function of a trigger is not defined in the schema (stub)

### ISSUE THREAD

**Issue by juliendelplanque** [olivierauverlot/PgMetadata#3]

**Comment by olivierauverlot** [comment]
Normally, it's not possible because PostgreSQL don't want delete a trigger function if it is used somewhere in a table. The only possibility is that the SQL schema has been modified with a code editor.

**Comment by olivierauverlot** [comment]
Really not possible. The schema must corrupted to have this problem. If the trigger function does not exist, the trigger is not created by PostgreSQL in the metadata tables.

**Comment by juliendelplanque** [comment]
Well, this error comes with a schema that has been loaded apparently without problem in the database. I will check the log I get while loading the schema to be sure.
