### ISSUE TITLE
Bug in PgFunctionExtractor

### ISSUE THREAD

**Issue by juliendelplanque** [olivierauverlot/PgMetadata#4]
<img width="962" alt="capture d ecran 2018-02-19 a 16 03 40" src="https://user-images.githubusercontent.com/8260456/36384127-8d372d6c-158e-11e8-815d-eabe264d75ce.png">

**Comment by olivierauverlot** [comment]
What is the function definition ?

**Comment by juliendelplanque** [comment]
I think this was the same bug as in #8 which is now fixed 🍭
